apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: central
spec:
  authorization:
    type: rbac
    server:
      - bootstrap.servers=kafka.central.svc.cluster.local:9073,kafka.east.svc.cluster.local:9073,kafka.west.svc.cluster.local:9073
      - confluent.controlcenter.schema.registry.url=https://schemaregistry.central.svc.cluster.local:8081,https://schemaregistry.east.svc.cluster.local:8081,https://schemaregistry.west.svc.cluster.local:8081
      - confluent.controlcenter.streams.consumer.client.rack=us-central1
      - confluent.controlcenter.streams.replication.factor=-1
  dataVolumeCapacity: 10Gi
  dependencies:
    kafka:
      authentication:
        jaasConfig:
          secretRef: credential
        type: plain
      bootstrapEndpoint: overridden:9073
      tls:
        enabled: true
    mds:
      authentication:
        bearer:
          secretRef: c3-mds-client
        type: bearer
      endpoint: https://kafka.central.svc.cluster.local:8090
      tls:
        enabled: true
      tokenKeyPair:
        secretRef: mds-token
    schemaRegistry:
      tls:
        enabled: true
      url: https://overridden:8081
  image:
    application: confluentinc/cp-enterprise-control-center:7.0.0
    init: confluentinc/confluent-init-container:2.2.0
  replicas: 1
  tls:
    autoGeneratedCerts: true