apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-with-sni
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  tls:
    - hosts:
        - # b0.$DOMAIN 
        - # b1.$DOMAIN
        - # b2.$DOMAIN
        - # kafka.$DOMAIN
  rules:
    - host: # b0.$DOMAIN
      http:
        paths:
          - backend:
              serviceName: kafka-0-internal
              servicePort: 9092
    - host: # b1.$DOMAIN
      http:
        paths:
          - backend:
              serviceName: kafka-1-internal
              servicePort: 9092
    - host: # b2.$DOMAIN
      http:
        paths:
          - backend:
              serviceName: kafka-2-internal
              servicePort: 9092
    - host: # kafka.$DOMAIN
      http:
        paths:
          - backend:
              serviceName: kafka-bootstrap
              servicePort: 9092
