apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"central.svc.cluster.local": ["34.68.73.68"], "west.svc.cluster.local": ["34.82.188.124"]}