apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"east.svc.cluster.local": ["34.139.159.61"], "west.svc.cluster.local": ["34.82.188.124"]}